name: Run performance tests
on: [pull_request,workflow_dispatch]
jobs:
  calculate:
    name: Run MATLAB tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
            release: R2023a
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: cd '.submodules/tests', addpath("../../main/"), assertSuccess(run_performance_tests)
      - name: Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.CO2SYS_GIST_KEY }}
          gist_id: c68eb447f90f281a543bca7ab1d7a56a
          file_path: tests/co2sys-performance-metrics.json
          file_type: text