name: Run small verification tests
on: [pull_request,workflow_dispatch]
jobs:
  calculate:
    name: Run MATLAB tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3 
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v1
        with:
            release: R2023a        
      - name: Install DVC
        run: |
            sudo wget https://dvc.org/deb/dvc.list -O /etc/apt/sources.list.d/dvc.list
            wget -qO - https://dvc.org/deb/iterative.asc | gpg --dearmor > packages.iterative.gpg
            sudo install -o root -g root -m 644 packages.iterative.gpg /etc/apt/trusted.gpg.d/
            rm -f packages.iterative.gpg
            sudo apt update
            sudo apt install dvc
      - name: Get small data files
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        run: dvc pull tests/small_data
      - name: Run script
        uses: matlab-actions/run-command@v1
        with:
          command: cd 'tests', addpath("./../main/"), assertSuccess(run_small_tests)